#pragma once
#define MAX_LEN_PIK 5
#define MAX_COUNT_PIK 4
#define MAX_LEN_ALL_PIK MAX_COUNT_PIK * MAX_LEN_PIK
#define MAX_LEN_LINE 50
#define START_LEN_NEURO 3
#define END_LEN_NEURO 50
#define MAX_LEN_LINE_NEURO END_LEN_NEURO-START_LEN_NEURO
#define MAX_COUNT_LINE 3